"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Server = { id: string; name: string; host: string; os: string; collection_interval: number };

export default function ServerSettingsPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState("");
  const [server, setServer] = useState<Server | null>(null);
  const [name, setName] = useState(""); const [host, setHost] = useState(""); const [os, setOs] = useState("windows"); const [interval, setInterval] = useState("5");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [code, setCode] = useState("");
  useEffect(() => { params.then(({ id: value }) => setId(value)); }, [params]);
  useEffect(() => { if (!id) return; fetch(`/api/servers/${id}/telemetry?limit=1`, { cache: "no-store" }).then(async r => { const j = await r.json(); if (!r.ok) throw new Error(j.error || "Unable to load server"); setServer(j.server); setName(j.server.name); setHost(j.server.host); setOs(j.server.os); setInterval(String(j.server.collection_interval)); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load server")); }, [id]);
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const r = await fetch(`/api/servers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, host, os, collection_interval: Number(interval) }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Unable to save changes"); setServer(j.server); setMessage("Server settings saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save changes"); } finally { setBusy(false); } }
  async function rotate() { if (!confirm("Rotate the agent credential? The currently installed agent will stop authenticating until it is updated.")) return; setBusy(true); setError(""); setMessage(""); setCode(""); try { const r = await fetch(`/api/servers/${id}/rotate`, { method: "POST" }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Unable to rotate credential"); setCode(j.enrollment_code); setMessage("Credential rotated. Install the new credential on the server."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to rotate credential"); } finally { setBusy(false); } }
  async function remove() { if (!confirm("Delete this server and all of its stored telemetry, logs, and errors? This cannot be undone.")) return; setBusy(true); setError(""); try { const r = await fetch(`/api/servers/${id}`, { method: "DELETE" }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Unable to delete server"); window.location.href = "/"; } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete server"); setBusy(false); } }
  return <div className="shell"><header className="topbar"><Link className="brand" href="/">Server<span>Monitor</span></Link><Link className="button" href={`/servers/${id}`}>Back to server</Link></header><main className="main narrow"><div className="eyebrow">Server settings</div><h1 className="title">{server?.name || "Server"}</h1><p className="muted lead">Update how this server is displayed and how often its agent reports telemetry.</p>
    <form className="form-card" onSubmit={save}><label>Server name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} required /></label><label>Hostname or IP<input value={host} onChange={e=>setHost(e.target.value)} maxLength={253} required /></label><div className="form-grid"><label>Operating system<select value={os} onChange={e=>setOs(e.target.value)}><option value="windows">Windows</option><option value="linux">Linux</option></select></label><label>Collection interval<select value={interval} onChange={e=>setInterval(e.target.value)}><option value="5">5 seconds</option><option value="10">10 seconds</option><option value="30">30 seconds</option></select></label></div>{message&&<div className="notice">{message}</div>}{error&&<div className="notice">{error}</div>}<button className="button primary full" disabled={busy}>{busy?"Saving…":"Save changes"}</button></form>
    <section className="form-card"><h2>Agent credential</h2><p className="muted">Rotate the credential if the current one may have been exposed. Rotation immediately invalidates the old credential.</p><button className="button" onClick={rotate} disabled={busy}>Rotate credential</button>{code&&<div className="notice"><strong>New one-time enrollment code</strong><br /><code>{code}</code><br /><small>Copy this now. It will not be shown again.</small></div>}</section>
    <section className="form-card"><h2>Danger zone</h2><p className="muted">Deleting a server permanently removes its telemetry, process history, logs, and errors.</p><button className="button" onClick={remove} disabled={busy}>Delete server</button></section>
  </main></div>;
}
