"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Server = { id:string; name:string; host:string; os:string; status:string; last_seen_at:string|null; created_at:string };

function age(value:string|null){ if(!value)return "Never"; const s=Math.max(0,Math.floor((Date.now()-Date.parse(value))/1000)); if(s<60)return `${s}s ago`; if(s<3600)return `${Math.floor(s/60)}m ago`; return `${Math.floor(s/3600)}h ago`; }
function ServerCard({server}:{server:Server}){ const online=server.status==="online"; return <Link className="server-card" href={`/servers/${server.id}`}><div className="server-head"><div><div className="status"><i className="dot" /> {online?"ONLINE":server.status.toUpperCase()}</div><div className="server-name">{server.name}</div><div className="ip">{server.host}</div></div><span className="muted arrow">›</span></div><div className="metrics"><div className="metric"><div className="metric-label">OS</div><div className="metric-value">{server.os}</div></div><div className="metric"><div className="metric-label">Last seen</div><div className="metric-value">{age(server.last_seen_at)}</div></div><div className="metric"><div className="metric-label">Status</div><div className="metric-value">{online?"Healthy":"Offline"}</div></div></div><div className="uptime"><span>Open dashboard</span><span>View live telemetry →</span></div></Link>; }

export default function Home(){ const [servers,setServers]=useState<Server[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); async function load(){try{const r=await fetch("/api/servers",{cache:"no-store"});const j=await r.json();if(r.status===401){setError("Sign in to view your servers.");return;}if(!r.ok)throw new Error(j.error||"Failed to load servers");setServers(j.servers||[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Failed to load servers");}finally{setLoading(false);}} useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]); return <div className="shell"><header className="topbar"><Link className="brand" href="/">Server<span>Monitor</span></Link><div className="top-actions"><Link className="button" href="/auth/login">Log in</Link><Link className="button primary" href="/auth/login?screen_hint=signup">Create account</Link></div></header><main className="main"><section className="hero"><div><div className="eyebrow">Infrastructure</div><h1 className="title">Your servers, at a glance.</h1><div className="muted">Monitor CPU, memory, GPU, network activity, logs and system health from one dashboard.</div></div><Link className="button primary" href="/servers/new">+ Add server</Link></section><div className="overview-strip"><div><span className="muted">Servers</span><strong>{servers.length}</strong></div><div><span className="muted">Online</span><strong className="healthy">{servers.filter(s=>s.status==="online").length}</strong></div><div><span className="muted">Active alerts</span><strong>—</strong></div><div><span className="muted">Agent status</span><strong className="healthy">{servers.length?"Monitoring":"Not configured"}</strong></div></div>{error&&<div className="notice">{error}</div>}{loading?<div className="notice">Loading servers…</div>:servers.length?<section className="server-grid">{servers.map(s=><ServerCard key={s.id} server={s}/>)}</section>:<section className="form-card"><h2>No servers yet</h2><p className="muted">Create a server enrollment to get a one-time agent command, then start monitoring it.</p><Link className="button primary" href="/servers/new">Add your first server</Link></section>}<div className="notice"><strong>Secure enrollment</strong> · Server passwords are not stored in the frontend. Agents authenticate with server-specific credentials.</div></main></div>; }
