"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Profile = { username:string; display_name:string; bio:string; avatar_url:string; is_public:boolean; github_username:string; github_url:string };
type Auth = { email:string; email_verified:boolean; picture:string };

export default function SettingsPage(){
  const [profile,setProfile]=useState<Profile>({username:"",display_name:"",bio:"",avatar_url:"",is_public:false,github_username:"",github_url:""});
  const [auth,setAuth]=useState<Auth>({email:"",email_verified:false,picture:""});
  const [newEmail,setNewEmail]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/profile",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load profile");setProfile(j.profile);setAuth(j.auth);setNewEmail(j.auth.email||"");}).catch(e=>setError(e instanceof Error?e.message:"Unable to load profile"));},[]);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to save profile");setProfile(j.profile);setMessage("Profile saved.");}catch(e){setError(e instanceof Error?e.message:"Unable to save profile");}finally{setBusy(false);}}
  async function passwordReset(){setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/account/password-reset",{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to send password email");setMessage(j.message);}catch(e){setError(e instanceof Error?e.message:"Unable to send password email");}finally{setBusy(false);}}
  async function changeEmail(e:React.FormEvent){e.preventDefault();if(!confirm("Change the account email and send a verification email to the new address?"))return;setBusy(true);setMessage("");setError("");try{const r=await fetch("/api/account",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:newEmail})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to change email");setMessage(j.message);}catch(e){setError(e instanceof Error?e.message:"Unable to change email");}finally{setBusy(false);}}
  async function deleteAccount(){if(!confirm("Delete your Server Monitor account and all servers and telemetry? This cannot be undone."))return;setBusy(true);setError("");try{const r=await fetch("/api/account",{method:"DELETE"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to delete account");window.location.href="/auth/logout";}catch(e){setError(e instanceof Error?e.message:"Unable to delete account");setBusy(false);}}
  return <div className="shell"><header className="topbar"><Link className="brand" href="/">Server<span>Monitor</span></Link><div className="top-actions"><Link className="button" href="/">Dashboard</Link><Link className="button" href="/auth/logout">Log out</Link></div></header><main className="main narrow"><div className="eyebrow">Account</div><h1 className="title">Profile & settings</h1><p className="muted lead">Configure your public profile and account security. Authentication credentials remain managed by Auth0.</p>
    {message&&<div className="notice">{message}</div>}{error&&<div className="notice">{error}</div>}
    <form className="form-card" onSubmit={save}><h2>Profile</h2><label>Username<input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})} maxLength={40} required /></label><label>Display name<input value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})} maxLength={80}/></label><label>Bio<textarea value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} maxLength={500} rows={4}/></label><label>Avatar URL<input value={profile.avatar_url} onChange={e=>setProfile({...profile,avatar_url:e.target.value})} maxLength={500} placeholder="https://…"/></label><label>GitHub username<input value={profile.github_username} onChange={e=>setProfile({...profile,github_username:e.target.value})} maxLength={80} placeholder="username"/></label><label>GitHub profile URL<input value={profile.github_url} onChange={e=>setProfile({...profile,github_url:e.target.value})} maxLength={300} placeholder="https://github.com/username"/></label><label className="check"><input type="checkbox" checked={profile.is_public} onChange={e=>setProfile({...profile,is_public:e.target.checked})}/> Make my profile public</label><button className="button primary full" disabled={busy}>{busy?"Saving…":"Save profile"}</button></form>
    <section className="form-card"><h2>Account security</h2><p className="muted">Signed in as <strong>{auth.email||"—"}</strong> · {auth.email_verified?"Email verified":"Email not verified"}</p><form onSubmit={changeEmail}><label>Account email<input type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} maxLength={254} required/></label><button className="button" disabled={busy || !newEmail}>Change email & verify</button></form><div className="settings-actions"><button className="button" onClick={passwordReset} disabled={busy}>Change password by email</button><Link className="button" href="/auth/login?prompt=login">Manage MFA / 2FA</Link></div><p className="muted small">Password changes use Auth0's verified email reset flow. Email changes send a verification email to the new address. MFA enrollment is handled by your Auth0 tenant's configured factors.</p></section>
    <section className="form-card"><h2>Connected apps</h2><p className="muted">Your GitHub profile can be displayed on your Server Monitor profile. GitHub identity linking requires the GitHub connection to be enabled in Auth0.</p><div className="settings-actions"><Link className="button" href="/auth/login?connection=github&returnTo=/settings">Connect GitHub</Link>{profile.github_username&&<span className="notice inline">Connected: @{profile.github_username}</span>}</div></section>
    <section className="form-card"><h2>Danger zone</h2><p className="muted">Delete your profile, servers, telemetry, logs and application account.</p><button className="button" onClick={deleteAccount} disabled={busy}>Delete account</button></section>
  </main></div>;
}
